/** @type {import('tailwindcss').Config} */
// Ported verbatim from the chosen Stitch "C" design (Material 3 token system) so the
// exported class names (bg-surface-container-highest, text-on-surface-variant, from-primary
// to-secondary, font-headline-md, px-container-margin, …) resolve identically.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#003824',
        'surface-container-lowest': '#060e20',
        'outline-variant': '#4d4354',
        'tertiary-fixed': '#d8e2ff',
        error: '#ffb4ab',
        'inverse-on-surface': '#283044',
        'surface-bright': '#31394d',
        'on-primary-container': '#400071',
        'on-background': '#dae2fd',
        primary: '#ddb7ff',
        'on-tertiary': '#002e6a',
        'on-secondary-container': '#00311f',
        'surface-dim': '#0b1326',
        'on-secondary-fixed-variant': '#005236',
        outline: '#988d9f',
        'on-primary-fixed': '#2c0051',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#adc6ff',
        'surface-tint': '#ddb7ff',
        'on-primary-fixed-variant': '#6900b3',
        'surface-container-low': '#131b2e',
        'surface-container-highest': '#2d3449',
        'on-tertiary-fixed': '#001a42',
        'secondary-fixed': '#6ffbbe',
        surface: '#0b1326',
        'on-surface': '#dae2fd',
        'secondary-container': '#00a572',
        secondary: '#4edea3',
        'surface-container-high': '#222a3d',
        'primary-container': '#b76dff',
        'error-container': '#93000a',
        'on-primary': '#490080',
        'on-error': '#690005',
        'surface-container': '#171f33',
        'on-surface-variant': '#cfc2d6',
        'primary-fixed': '#f0dbff',
        'surface-variant': '#2d3449',
        'inverse-primary': '#842bd2',
        'tertiary-container': '#4d8eff',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#004395',
        'inverse-surface': '#dae2fd',
        tertiary: '#adc6ff',
        background: '#0b1326',
        'on-tertiary-container': '#00285d',
        'primary-fixed-dim': '#ddb7ff',
        'secondary-fixed-dim': '#4edea3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        gutter: '16px',
        md: '16px',
        'container-margin': '20px',
        xxl: '64px',
        unit: '4px',
        xl: '40px',
        lg: '24px',
        xs: '4px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['"Plus Jakarta Sans"'],
        'headline-lg': ['"Plus Jakarta Sans"'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
        'headline-md': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'display-lg': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'display-lg-mobile': ['36px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
